#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet/arrayable'

class A
  include Neuronet::Arrayable

  def initialize
    @array = [1, 2, 3]
  end

  private

  def to_a = @array
end

class TestArrayable < Test::Unit::TestCase
  # rubocop: disable Metrics, Style
  def test_arrayable
    a = A.new
    b = []
    a.each { b << it }
    assert_equal b, [1, 2, 3]
    a.each_with_index do |n, i|
      assert_equal i + 1, n
    end
    assert_equal a[1], 2
    assert_equal a.map(&:to_s), %w[1 2 3]
    assert_equal a.size, 3
    assert_equal a.reverse, [3, 2, 1]
  end
  # rubocop: enable Metrics, Style
end
