#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

class TestConnection < Test::Unit::TestCase
  # rubocop: disable Metrics
  def test_connection_nil
    neuron = Neuronet::Neuron.new
    weight = 0.0
    connection = Neuronet::Connection.new(neuron, weight)
    assert_equal connection.weight, weight
    assert_equal connection.neuron, neuron
    assert_equal neuron.activation, 0.5
    assert_equal connection.value, 0.0
    connection.weight = 1.0
    assert_equal connection.value, 0.5
    connection.weight = 2.0
    assert_equal connection.value, 1.0
  end
  # rubocop: enable Metrics
end
