#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'
# Also:
# require 'cucumber'

# Cucumber Tests
class TestCucumber < Test::Unit::TestCase
  def test_cucumber
    flunk 'Rotten cucumber!'.red unless system 'cucumber -f progress'
  end
end
