#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

class TestConfig < Test::Unit::TestCase
  def test_config
    # save
    bias = Neuronet::Config.bias_clamp
    weight = Neuronet::Config.weight_clamp
    # change
    Neuronet::Config.bias_clamp = 12.3
    Neuronet::Config.weight_clamp = 4.56
    # verify change
    assert_equal Neuronet::Config.bias_clamp, 12.3
    assert_equal Neuronet::Config.weight_clamp, 4.56
    # restore
    Neuronet::Config.bias_clamp = bias
    Neuronet::Config.weight_clamp = weight
    # verify restore
    assert_equal Neuronet::Config.bias_clamp, bias
    assert_equal Neuronet::Config.weight_clamp, weight
  end
end
