#!/usr/bin/env ruby
require 'test/unit'
require 'colorize'
require 'neuronet'

class TestEpsilon < Test::Unit::TestCase
  include Neuronet
  EPSILON = 0.5**13

  def test_epsilon
    # EPSILON is parts per thousands...
    assert_equal 8192.0, 1.0 / EPSILON
  end

  def test_average_mju
    ff = FeedForward.new([4, 4, 4, 4])

    # Set all weights to 1.0, biases to 0.0
    ff.each do |layer|
      layer.each do |neuron|
        neuron.value = 0.0
        neuron.bias = 0.0
        neuron.connections.each do |connection|
          connection.weight = 1.0
        end
      end
    end

    target = ff * [0.0, 0.0, 0.0, 0.0]
    expected_error = ff.average_mju * EPSILON

    # Set all weights to 1.0 + epsilon, biases to epsilon
    ff.each do |layer|
      layer.each do |neuron|
        neuron.value = 0.0
        neuron.bias = EPSILON
        neuron.connections.each do |connection|
          connection.weight = 1.0 + EPSILON
        end
      end
    end

    deviant = ff * [0.0, 0.0, 0.0, 0.0]
    error = deviant[0] - target[0]

    # Experimentally observed error is the expected_error to 3 digits.
    assert_equal '%.3g' % expected_error, '%.3g' % error
  end

  def test_expected_mju
    ff = FeedForward.new([128, 128, 128, 128])

    # Randomly set all weights to (+/-)1.0, biases to 0.0
    ff.each do |layer|
      layer.each do |neuron|
        neuron.value = 0.0
        neuron.bias = 0.0
        neuron.connections.each do |connection|
          connection.weight = rand > 0.5 ? 1.0 : -1.0
        end
      end
    end

    target = ff * [0.0, 0.0, 0.0, 0.0]
    expected_error = ff.expected_mju * EPSILON

    # Set all weights to weight + epsilon, biases to epsilon
    ff.each do |layer|
      layer.each do |neuron|
        neuron.value = 0.0
        neuron.bias = EPSILON
        neuron.connections.each do |connection|
          connection.weight += EPSILON
        end
      end
    end

    deviant = ff * [0.0, 0.0, 0.0, 0.0]
    error = deviant[0] - target[0]

    # Experimentally observed error is less than the expected_error.
    assert error.abs < expected_error.abs
    # Expected error is not more than 100 times the observed error.
    assert expected_error.abs / error.abs < 100.0
    # And it's typically less than 10 times the observed error.
    if expected_error.abs / error.abs > 10.0
      puts 'Got error greater than 10 times expected error.'.colorize(:red)
    end
  end

  def r4
    4.times.sum { rand }
  end

  def test_really
    # Arbitrary layers:
    layers = (2 + r4).to_i.times.inject([]) { |a,_| a << (1+r4+r4+r4+r4).to_i }
    puts "Testing FF #{layers.inspect}".colorize(:green)
    ff = FeedForward.new(layers)

    # Arbitrary weights and biases:
    ff.each do |layer|
      layer.each do |neuron|
        neuron.bias = r4 - r4
        neuron.connections.each do |connection|
          connection.weight = r4 - r4
        end
      end
    end

    # Arbitrary input values:
    values = ff.first.map { r4 - r4 }
    puts "With input #{values.map{_1.round(4)}.inspect}".colorize(:green)

    # Target:
    target = ff * values
    puts "Output is #{target.map{_1.round(4)}.inspect}".colorize(:green)

    # Expected errors:
    expected_errors = ff.last.map { Neuron.mju(_1) * EPSILON }
    puts "Expected errors is #{expected_errors.map{'%.2e' % _1}.inspect}"
         .colorize(:magenta)

    # Set all weights and biases to  += epsilon:
    ff.each do |layer|
      layer.each do |neuron|
        neuron.bias += EPSILON
        neuron.connections.each do |connection|
          connection.weight += EPSILON
        end
      end
    end

    # Deviant:
    deviant = ff * values
    puts "Deviant is #{deviant.map{_1.round(4)}.inspect}".colorize(:green)

    # Errors:
    errors = deviant.zip(target).map {|a,b| a-b}
    puts "Actual errors is #{errors.map{'%.2e' % _1}.inspect}"
         .colorize(:magenta)

    # Experimentally observed error is the expected_error to 2 digits.
    assert_equal expected_errors.map{'%.1e' % _1}, errors.map{'%.1e' % _1}
    # Experimentally observed error is the expected_error to 3 digits.
    # Happens sometimes...
    unless expected_errors.map{'%.2e' % _1} == errors.map{'%.2e' % _1}
      puts 'An error differed at 3 significant figures.'.colorize(:red)
    end
  end
end
