#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

# Neuronet::FeedForward is mostly tested in:
#     examples/test_feed_forward
# Just doing some unit sanity checks.
class TestFeedForward < Test::Unit::TestCase
  def test_feed_forward_raises
    # rubocop: disable Lint
    e = assert_raise(RuntimeError) do
      nd = Neuronet::FeedForward.new(3, 3)
    end
    # rubocop: enable Lint
    assert_equal e.message, 'Need at least 3 layers'
  end

  # rubocop: disable Metrics
  def test_feed_forward
    nd = Neuronet::FeedForward.new(3, 6, 2)
    # right classes
    assert_equal nd.input_layer.class, Neuronet::Layer
    assert_equal nd.output_layer.class, Neuronet::Layer
    assert_equal nd.hidden_layers.class, Array
    # right sizes
    assert_equal nd.input_layer.size, 3
    assert_equal nd.output_layer.size, 2
    assert_equal nd.hidden_layers.size, 1
    assert_equal nd.hidden_layers[0].size, 6
    # quick computations test, but this is really tested in /examples/.
    assert_equal nd.values, [0.0, 0.0]
    values = nd * [0.0, 0.0, 0.0]
    assert_equal values, [0.0, 0.0]
    layers = nd.to_a
    assert_equal layers.size, 3
    assert layers[0].is_a? Neuronet::Layer
    assert layers[1].is_a? Neuronet::Layer
    assert layers[2].is_a? Neuronet::Layer
  end
  # rubocop: enable Metrics
end
