#!/usr/bin/env ruby
require 'test/unit'
require 'neuronet'
include Neuronet

class TestGaussian < Test::Unit::TestCase
  def test_gaussian
    inputs = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    gaussian = Gaussian.new.set inputs
    assert_equal 5.5, gaussian.center
    assert_equal Math.sqrt(82.5/(10-1.0)), gaussian.spread
    mapped = gaussian.mapped(inputs)
    assert_equal 0.0, mapped.sum.round(14), "It's centered about zero?"
    outputs = gaussian.unmapped mapped
    assert_equal inputs.map{|_|'%.15g' % _}, outputs.map{|_|'%.15g' % _}
  end
end
