#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

class TestInputLayer < Test::Unit::TestCase
  # rubocop: disable Metrics
  def test_input_layer
    a = Neuronet::InputLayer.new(3)
    b = Neuronet::MiddleLayer.new(2)
    b.connect(a)
    n0 = a[0]
    assert_equal n0.class, Neuronet::InputNeuron
    assert_equal n0.connections.size, 0
    refute a.respond_to? :values
    a.set [1.0, 0.0, -1.0]
    assert_equal(a.map { it.activation.round(2) }, [0.73, 0.5, 0.27])
    refute a.respond_to? :update
  end
  # rubocop: enable Metrics
end
