#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

class TestInputNeuron < Test::Unit::TestCase
  # rubocop: disable Metrics
  def test_input_neuron
    a = Neuronet::InputNeuron.new
    assert_nil a.bias
    assert_equal a.activation, 0.5
    assert_equal a.connections, []
    assert a.connections.frozen?
    assert_nil a.value
    refute a.respond_to? :connect
    a.set(1.0)
    v = Neuronet::Squash.squash(1.0)
    assert_equal a.activation, v
    assert_nil a.backpropagate(rand) # hard-coded nil on anything
    refute a.respond_to? :update
  end
  # rubocop: enable Metrics
end
