#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

class TestLayer < Test::Unit::TestCase
  # rubocop: disable Metrics
  def test_layer
    a = Neuronet::Layer.new(3)
    b = Neuronet::Layer.new(2)
    a.connect(b)
    n0 = a[0]
    assert_equal n0.class, Neuronet::Neuron
    assert_equal n0.connections.size, 2
    assert_equal a.values, [0.0, 0.0, 0.0]
    a.set [1.0, 0.0, -1.0]
    assert_equal(a.map { it.activation.round(2) }, [0.73, 0.5, 0.27])
    a.update
    assert_equal(a.map { it.activation.round(2) }, [0.5, 0.5, 0.5])
  end
  # rubocop: enable Metrics
end
