#!/usr/bin/ruby
require 'test/unit'
require 'rubbish'

# This just checks that the lexicon of the files in
#   lib/**.rb
# has not changed.  No dictionary maintainance required.
# Just ensure you have no typos...
# then set the hex to the observed value.
# BTW, if spell returns no errors, hex is
#   d41d8cd98f00b204e9800998ecf8427e
class TestLexicon < Test::Unit::TestCase
  def test_lexicon
    hex = Rubbish.fish('cat lib/**.rb | spell | md5sum').split.first
    assert_equal 'ab2a9e734e4a8243a3729d57f17c4342', hex, 'Hexdigest All'
  end

  def test_lexicon_code
    hex = Rubbish.fish("cat lib/**.rb | egrep -v '^\\s*#' | spell | md5sum").split.first
    assert_equal '4fbcdd5af3dff5c4feedad280ac0051d', hex, 'Hexdigest Code'
  end

  def test_lexicon_comments
    hex = Rubbish.fish("cat lib/**.rb | egrep '^\\s*#' | spell | md5sum").split.first
    assert_equal 'd839df25a8d67a096d1604fd3df7c77b', hex, 'Hexdigest Comments'
  end
end
