#!/usr/bin/ruby
require 'test/unit'
require 'rubbish'

# This just checks that the lexicon of the files in
#   lib/**.rb
# has not changed.  No dictionary maintainance required.
# Just ensure you have no typos...
# then set the hex to the observed value.
# BTW, if spell returns no errors, hex is
#   d41d8cd98f00b204e9800998ecf8427e
class TestLexicon < Test::Unit::TestCase
  def test_lexicon
    hex = Rubbish.fish('cat lib/**.rb | spell | md5sum').split.first
    assert_equal '24844e9340bf3d77ed19e1c86496d93a', hex, 'Hexdigest All'
  end

  def test_lexicon_code
    hex = Rubbish.fish("cat lib/**.rb | egrep -v '^\\s*#' | spell | md5sum").split.first
    assert_equal '2e367b06dae1952bda2882c65d9ac4fb', hex, 'Hexdigest Code'
  end

  def test_lexicon_comments
    hex = Rubbish.fish("cat lib/**.rb | egrep '^\\s*#' | spell | md5sum").split.first
    assert_equal '33d8f4d065037178df2331f312151101', hex, 'Hexdigest Comments'
  end
end
