#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

module InsideFloats
  refine Float do
    def inside?(min, max)
      (self > min) && (self < max)
    end
  end
end

class TestNoisyBackpropagate < Test::Unit::TestCase
  # rubocop: disable Metrics
  def test_clamp
    assert_equal Neuronet::NoisyBackpropagate.clamp, 12.0
    Neuronet::NoisyBackpropagate.clamp = 3.0
    assert_equal Neuronet::NoisyBackpropagate.clamp, 3.0
    Neuronet::NoisyBackpropagate::M.clamp = 12.0
    assert_equal Neuronet::NoisyBackpropagate::M.clamp, 12.0
    assert_equal Neuronet::NoisyBackpropagate.clamp, 12.0
  end

  using InsideFloats

  # rubocop: disable Lint
  def test_backpropagate
    a = Neuronet::NoisyNeuron.new
    b = Neuronet::NoisyNeuron.new
    b.connect a
    assert_equal a.bias, 0.0
    assert_equal a.activation, 0.5
    assert_equal b.bias, 0.0
    assert_equal b.activation, 0.5
    assert_equal b.connections[0].weight, 0.0
    b.backpropagate(0.2)
    assert a.bias.inside?(0.0, 0.4) # definitely in this interval but...
    refute(a.bias == 0.2) # very unlikely exactly this!
    assert_equal a.activation, 0.5
    assert b.bias.inside?(0.0, 0.4)
    refute(b.bias == 0.2)
    assert_equal b.activation, 0.5
    # activation * (error + noise)
    assert b.connections[0].weight.inside?(0.0, 0.2)
    refute b.connections[0].weight == 0.1
    # test bias clamping:
    b.bias = 12.0
    b.backpropagate(0.2)
    assert_equal b.bias, 12.0
    assert b.connections[0].weight.inside?(0.1, 0.3)
    refute b.connections[0].weight == 0.2
    # test weight clamping:
    b.connections[0].weight = -50.0
    b.backpropagate(0.2)
    assert_equal b.connections[0].weight, -12.0
  end
  # rubocop: enable Lint
  # rubocop: enable Metrics
end
