#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

module InsideFloats
  refine Float do
    def inside?(min, max)
      (self > min) && (self < max)
    end
  end
end

class TestNoisyBackpropagate < Test::Unit::TestCase
  using InsideFloats

  # rubocop: disable Metrics
  # rubocop: disable Lint
  def test_backpropagate
    a = Neuronet::NoisyNeuron.new
    b = Neuronet::NoisyNeuron.new
    b.connect a
    assert_equal a.bias, 0.0
    assert_equal a.activation, 0.5
    assert_equal b.bias, 0.0
    assert_equal b.activation, 0.5
    assert_equal b.connections[0].weight, 0.0
    b.backpropagate(0.1)
    assert a.bias.inside?(0.0, 0.2) # definitely in this interval but...
    refute(a.bias == 0.1) # very unlikely exactly this!
    assert_equal a.activation, 0.5
    assert b.bias.inside?(0.0, 0.2)
    refute(b.bias == 0.1)
    assert_equal b.activation, 0.5
    assert b.connections[0].weight.inside?(0.0, 0.2)
    refute b.connections[0].weight == 0.1
  end

  def test_clamping
    a = Neuronet::NoisyNeuron.new
    b = Neuronet::NoisyNeuron.new
    b.connect a
    bmax = Neuronet::Clamp.bias
    b.bias = bmax
    b.backpropagate(0.1)
    assert_equal b.bias, bmax
    assert b.connections[0].weight.inside?(0.0, 0.2)
    refute b.connections[0].weight == 0.1
    # test weight clamping:
    wmax = Neuronet::Clamp.weight
    b.connections[0].weight = -(2 * wmax)
    b.backpropagate(0.1)
    assert_equal b.connections[0].weight, -wmax
  end
  # rubocop: enable Lint
  # rubocop: enable Metrics
end
