#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

class TestNoisyNeuron < Test::Unit::TestCase
  # It's just a neuron with NoisyBackpropagate
  def test_noisy_neuron
    assert_nothing_raised do
      Neuronet::NoisyNeuron.new
    end
  end
end
