#!/usr/bin/env ruby
# frozen_string_literal: true

require 'colorize'
require 'test/unit'
require 'neuronet'

class TestNetworkStats < Test::Unit::TestCase
  def test_expected_nju
    nd = Neuronet::Deep.new(3, 3, 3, 3)
    nju = nd.expected_nju.round(2)
    assert_equal nju, 4.05
  end

  def random_weight
    (rand + rand + rand) - (rand + rand + rand)
  end

  # rubocop: disable Metrics
  def test_njus
    nd = Neuronet::Deep.new(3, 3, 3, 3)
    nd[1..].each do |layer|
      layer.each do |neuron|
        neuron.connections.each do |connection|
          connection.weight = random_weight
        end
      end
    end
    njus = nd.njus
    avg = njus.sum / 3.0
    assert avg.between?(2.0, 6.07) # very likely true
  end
  # rubocop: enable Metrics
end
