#!/usr/bin/ruby
require 'test/unit'

DICTIONARY = '.dictionary'
README     = 'README.md'

class TestReadmeSpell < Test::Unit::TestCase
  def test_readme_rocket_test
    return unless File.exist? README
    errors = `egrep '^[[:graph:]]' #{README} | spell | sort -u`.split
    if File.exist? DICTIONARY
      cleared = File.read(DICTIONARY).split
      errors.delete_if{|_|cleared.include?_}
    end
    assert_empty errors.join(' '), "Possible spelling errors"
  end
end
