#!/usr/bin/env ruby
require 'test/unit'
require 'colorize'

class TestRubySyntax < Test::Unit::TestCase
  def test_ruby_syntax
    # Get all files in git...
    `git ls-files`.lines.map(&:chomp)
    # select rb files, skip others(md,txt,etc.), and select ruby executables...
    .select{/\.rb$/.match?_1 or (!/\.\w*$/.match?_1 and _bang_ruby?_1)}
    # and iterate!
    .each do |fn|
      msg = "\n#### SYNTAX: ####\n# #{fn}\n#################".red
      assert system("ruby -c #{fn} >/dev/null"), msg
    end
  end
  private
  def _bang_ruby?(fn)
    return false if File.directory?(fn) || !File.executable?(fn)
    /^#!.*\bruby$/.match? File.read(fn,80).lines[0].rstrip
  end
end
