#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'colorize'

class TestRubySyntax < Test::Unit::TestCase
  def test_ruby_syntax
    # Get all files in git...
    `git ls-files`.lines.map(&:chomp)
                  .select { /\.rb$/.match?(it) || _bang_ruby?(it) }
                  .each do |filename|
      msg = "\n#### SYNTAX: ####\n# #{filename}\n#################".red
      assert system("ruby -c #{filename} >/dev/null"), msg
    end
  end

  private

  def _bang_ruby?(filename)
    return false if /\.\w*$/.match?(filename) ||
                    File.directory?(filename) ||
                    !File.executable?(filename)

    /^#!.*\bruby$/.match? File.read(filename, 80).lines[0].rstrip
  end
end
