#!/usr/bin/env ruby
# frozen_string_literal: true

require 'test/unit'
require 'neuronet'

class TestTrainable < Test::Unit::TestCase
  # rubocop: disable Metrics
  def test_autoloads
    assert([
      Neuronet::Perceptron,
      Neuronet::MLP,
      Neuronet::Deep,
      Neuronet::FeedForward
    ].all? { it.instance_methods.include? :pairs })
    assert([
      Neuronet::Perceptron,
      Neuronet::MLP,
      Neuronet::Deep,
      Neuronet::FeedForward
    ].all? { it.instance_methods.include? :train })
    assert([
      Neuronet::Perceptron,
      Neuronet::MLP,
      Neuronet::Deep,
      Neuronet::FeedForward
    ].all? { it.instance_methods.include? :pivot })
  end

  # rubocop: disable Style
  # Using CAPTURE it as a global cache
  CAPTURE = []
  # rubocop: enable Style

  PAIRS = [
    [[1], [2]],
    [[2], [4]],
    [[3], [6]]
  ].freeze
  EXPECTED_PAIRS_CAPTURE = [
    [[1], [2], { nju: 1 }],
    [[2], [4], { nju: 1 }],
    [[3], [6], { nju: 1 }]
  ].freeze
  EXPECTED_TRAIN_CAPTURE = [
    [[2]],
    [[4]],
    [[6]]
  ].freeze

  def test_pairs
    mlp = Neuronet::MLP.new(1, 1, 1)
    # Override mlp's train method to capture pairs
    def mlp.train(*args) = ::TestTrainable::CAPTURE << args
    CAPTURE.clear
    mlp.pairs PAIRS, nju: 1
    assert_equal CAPTURE.sort, EXPECTED_PAIRS_CAPTURE
  end
  # rubocop: enable Metrics

  def test_pivot
    p = Neuronet::Perceptron.new(1, 1) # just anything to test pivot
    errors = [1, -2, 3, -4, -3, 2, -1]
    e, i = p.pivot(errors)
    assert_equal e, -4
    assert_equal i, 3
    assert_equal e, errors[i] # sanity check :P
  end

  class TestSSE
    include Neuronet::Trainable

    def *(other) = other.map { (it * it) - it }
  end

  TEST_SSE = [
    [[1, 5, -4],  [5, 3, -5]],
    [[0, 1, -1],  [3, 1, -3]],
    [[2, 2, -5],  [0, 1, 0]],
    [[3, 1, -4],  [-3, 6, -3]]
  ].freeze

  # rubocop: disable Metrics
  def test_sum_of_squared_errors
    tsse = TestSSE.new
    sse = tsse.sum_of_squared_errors(TEST_SSE)
    outputs = TEST_SSE.map { |i, _o| i.map { (it * it) - it } }
    sum = 0
    outputs.each_with_index do |actuals, i|
      targets = TEST_SSE[i][1]
      actuals.each_with_index do |actual, j|
        target = targets[j]
        error = target - actual
        sum += error * error
      end
    end
    assert_equal sse, sum
  end
  # rubocop: enable Metrics
end
