#!/usr/bin/env ruby
# frozen_string_literal: true

cmd = ARGV.shift || 'pane'
list = *ARGV
list = `tmux list-panes -F '#P'`.split if list.empty?
list.each do |i|
  running = `tmux display -t ":.#{i}" -p '\#{pane_current_command}'`.chomp
  `tmux send-keys -t ":.#{i}" "#{cmd}" Enter` if running == 'fish'
end
