#!/usr/bin/env ruby
# frozen_string_literal: true

require 'help_parser'

OPTIONS = HelpParser['0.0.0', <<~HELP]
  Usage:
    test_logical_and [:options+]
  Options:
    --mult=FLOAT
  Types:
    FLOAT   /^\\d+\\.\\d+$/
HELP

require 'neuronet'

# Testing logical "and".
# Also, comparing MLP.pairs vs MLP.pairs_pivot vs MLP.pairs_random.
# The random nature of the training for this example is such that
# on any one run, any of the three methods can win, but
# the statistics shows that pivot does work!

PAIRS = [
  [[1, 1], [1]],
  [[-1, 1], [-1]],
  [[1, -1], [-1]],
  [[-1, -1], [-1]]
].freeze

def benchmarking(mlp, msg)
  iterations = 0
  start = Time.now
  while PAIRS.any? { |inp, tar| (mlp * inp).map { it.round(2) } != tar }
    yield
    iterations += 1
  end
  elapsed = Time.now - start
  ips = iterations / elapsed
  puts "#{msg}  Time: #{elapsed}  Iterations: #{iterations}  IPS: #{ips.round}"
  elapsed
end

def new_mlp
  Neuronet::MLP.new(2, 4, 1, middle_neuron: Neuronet::NoisyMiddleNeuron)
end

def remove_outliers(times)
  3.times do
    min, max = times.minmax
    times.delete(min)
    times.delete(max)
  end
end

# Sanity check: assert that mlp's expected nju is 4.0!
# rubocop: disable Lint/FloatComparison
raise 'Unexpected nju' unless new_mlp.expected_nju == 4.0
# rubocop: enable Lint/FloatComparison

if (mult = OPTIONS.mult&.to_f)
  Neuronet::Config.nju_mult = mult
end
NJU = Neuronet::Config.nju_mult * 4.0

np = [] # no pivot
wp = [] # with pivot
pn = [] # pivot and nju
rn = [] # random
rw = [] # random with nju
36.times do
  mlp = new_mlp
  t = benchmarking(mlp, '     Pivot-less:') { mlp.pairs(PAIRS, NJU) }
  np << t
  mlp = new_mlp
  t = benchmarking(mlp, '          Pivot:') { mlp.pairs_pivot(PAIRS) }
  wp << t
  mlp = new_mlp
  t = benchmarking(mlp, ' Pivot with mju:') { mlp.pairs_pivot(PAIRS, NJU) }
  pn << t
  mlp = new_mlp
  t = benchmarking(mlp, '         Random:') { mlp.pairs_random(PAIRS) }
  rn << t
  mlp = new_mlp
  t = benchmarking(mlp, 'Random with nju:') { mlp.pairs_random(PAIRS, NJU) }
  rw << t
end

remove_outliers(np)
remove_outliers(wp)
remove_outliers(pn)
remove_outliers(rn)
remove_outliers(rw)

puts "Neuronet::Config.nju_mult = #{Neuronet::Config.nju_mult}"
puts '# Total time'
puts "       No-Pivot: #{np.sum}"
puts "          Pivot: #{wp.sum}"
puts " Pivot with nju: #{pn.sum}"
puts "         Random: #{rn.sum}"
puts "Random with nju: #{rw.sum}"
