#!/usr/bin/env ruby
# frozen_string_literal: true

require 'help_parser'

OPTIONS = HelpParser['0.0.0', <<~HELP]
  Usage:
    test_logical_and [:options+]
  Options:
    --nju=FLOAT
  Types:
    FLOAT   /^\\d+\\.\\d+$/
HELP

require 'neuronet'

PAIRS = [
  [[1, 1], [1]],
  [[-1, 1], [-1]],
  [[1, -1], [-1]],
  [[-1, -1], [-1]]
].freeze

def benchmarking(mlp, msg)
  iterations = 0
  start = Time.now
  while PAIRS.any? { |inp, tar| (mlp * inp).map { it.round(2) } != tar }
    yield
    iterations += 1
  end
  elapsed = Time.now - start
  ips = iterations / elapsed
  puts "#{msg}  Time: #{elapsed}  Iterations: #{iterations}  IPS: #{ips.round}"
  elapsed
end

def new_mlp
  Neuronet::MLP.new(2, 4, 1, middle_neuron: Neuronet::NoisyMiddleNeuron)
end

def remove_outliers(times)
  6.times do
    max = times.max
    times.delete(max)
  end
end

# Sanity check: assert that mlp's expected nju is 4.0!
# rubocop: disable Lint/FloatComparison
raise 'Unexpected nju' unless new_mlp.expected_nju == 4.0
# rubocop: enable Lint/FloatComparison

NJU = OPTIONS.nju&.to_f || 4.0

times = []
36.times do
  mlp = new_mlp
  t = benchmarking(mlp, '*') { mlp.pairs(PAIRS, nju: NJU) }
  times << t
end

remove_outliers(times)

puts "NJU = #{NJU}"
puts "Total time: #{times.sum}"
